### ISSUE TITLE
Add padding between content and footer

### ISSUE THREAD

**Issue by diegoprudencios** [WeAreNewt/re-meme#126]
- [ ] add 120px always between the content and the footer

<img width="1909" alt="Screenshot 2022-08-31 at 16 51 16" src="https://user-images.githubusercontent.com/100305353/187712157-3b4d1ccb-90e0-470c-a9df-360fc0b3142d.png">

**Comment by 0xjim** [comment]
Combined with https://github.com/WeAreNewt/re-meme/issues/116
