### ISSUE TITLE
Sharing buttons do not work 

### ISSUE THREAD

**Issue by AdamGencel** [WeAreNewt/re-meme#26]
None of the buttons highlighted in the red square are working. ![image](https://user-images.githubusercontent.com/42351914/173350185-10552c92-f1a8-48e9-833c-9c736c885cfc.png)

**Comment by 0xjim** [comment]
Same functionality as this issue: https://github.com/WeAreNewt/Memixer/issues/39

**Comment by 0xjim** [comment]
Updating this ticket with the new build:
- 'Share on Lenster' doesn't work post-mint
- Copy meme URL on memixer doesn't work
- Share to twitter doesn't work; you can use the copy from this issue: https://github.com/WeAreNewt/Memixer/issues/55
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/84038320/182151721-e7837849-cdf1-4e38-94d1-687708ff2e48.png">
