### ISSUE TITLE
links in the footer do not lead to where they should 

### ISSUE THREAD

**Issue by AdamGencel** [WeAreNewt/re-meme#92]
![Screenshot 2022-08-18 at 13 52 47](https://user-images.githubusercontent.com/42351914/185388252-aa4c766f-c078-418c-9eba-2d425d53579c.png)

**Comment by 0xjim** [comment]
Duplicate with this: https://github.com/WeAreNewt/Memixer/issues/76

in active branch waiting for text from legal
