### ISSUE TITLE
Can't access your own profile 

### ISSUE THREAD

**Issue by AdamGencel** [WeAreNewt/re-meme#93]
![Screenshot 2022-08-18 at 13 53 33](https://user-images.githubusercontent.com/42351914/185388589-fe2b3c94-350e-4973-8626-6987bce87d6a.png)

**Comment by 0xjim** [comment]
Thanks for flagging. We're purposefully not building a profile page for MVP. However, @JoaquinBattilana / @arttu0  it shows on the UI that it is a clickable button. We should remove that.
